spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        min-idle: 0
        max-idle: 20
    timeout: 5000
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  resources:
    cache:
      period: 0
  devtools:
    restart:
      enabled: true

